## Deep Learning (Pytorch)

Before we can start this lesson there are two things we need to do. First, we need to import the libraries that we'll need to get our work done.

In [4]:
import os
import sys

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

import PIL
import torch
import torchvision

from PIL import Image
from torchvision import transforms

It's a good idea to print out the version numbers for your libraries, including Python. That way, anyone who reviews your work will know exactly what software is used in case they want to reproduce it.

In [3]:
# if you don't have it installed, use the command below

# %pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.


In [5]:
print("Platform:", sys.platform)
print("Python version:", sys.version)
print("---")
print("matplotlib version:", matplotlib.__version__)
print("pandas version:", pd.__version__)
print("PIL version:", PIL.__version__)
print("torch version:", torch.__version__)
print("torchvision version:", torchvision.__version__)

Platform: win32
Python version: 3.10.20 | packaged by Anaconda, Inc. | (main, Mar 11 2026, 17:42:35) [MSC v.1942 64 bit (AMD64)]
---
matplotlib version: 3.10.8
pandas version: 2.3.3
PIL version: 12.1.1
torch version: 2.11.0+cpu
torchvision version: 0.26.0+cpu


### Objectives:

- Check important attributes of tensors, such as size, data type, and device.
- Manipulate tensors through slicing.
- Perform mathematical operations with tensors, including matrix multiplication and aggregation calculations.

New Terms: **Attribute, Class, Method, Tensor**

### Working with Tensors in PyTorch

### What are Tensors?
The term **tensor** comes from mathematics. It refers to an array of values organized into one or more dimensions. In Pytorch it's built for **deep learning**. 

In Python, there are several libraries for creating and manipulating tensors. In this example, we'll use PyTorch, which is built for **deep learning**. We'll build our computer visions with PyTorch.

In this section, we'll get familiar with **tensors** and what we can do with them. We'll begin making a 2-dimensional tensor from a nested list.

In [6]:
#Working with Tensors in PyTorch using the nested list `my_nested_values` to create the tensor my_tensor.
my_nested_list = [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ]
type(my_nested_list)
my_tensor = torch.Tensor(my_nested_list)

print("my_tensor class:", type(my_tensor))
print(my_tensor)

my_tensor class: <class 'torch.Tensor'>
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


**Note that** a PyTorch tensor is a class: `Tensor()`. Like any class, it has attributes that can provide us with information. For instance, the `.shape` attribute tells us the dimensions of the tensor, and the `.dtype` attribute tells us the data type of the values stored inside the tensor.

In [7]:
print("my_tensor shape:", my_tensor.shape)

print("my_tensor dtype:", my_tensor.dtype)

my_tensor shape: torch.Size([4, 3])
my_tensor dtype: torch.float32


**Tensors** also have a `.device` attribute, which specifies the hardware on which it's stored. By default, tensors are created on the computer's CPU. Let's check if that's the case for `my_tensor`.

### Switching devices
We won't be able to see a performance boost with this tensor because it's already very small. However, switching devices will definitely speed up data preprocessing and models when dealing with larger sets of data.

Some computers come with GPUs, which allow for bigger and faster model building. In PyTorch, the cuda package is used to access GPUs on Linux and Windows machines; mps is used on Macs. Let's check what's available on our machines.

In [9]:
# Check if GPUs available via `cuda`
print("CUDA Available:", torch.cuda.is_available())
# print("GPU Name:", torch.cuda.get_device_name(0))

CUDA Available: False


From the output above, I now have a Tesla T4 GPU. I'm now running on `NVIDIA Tesla T4`

Key characteristics:

- 16GB GDDR6 VRAM
- Optimized for deep learning inference/training
- Common in Colab Pro / free-tier GPUs
- CUDA-compatible (PyTorch works natively)

To properly use the GPU, we have to move our model to our GPU.

In [11]:
# #Getting the cuda device
# device = torch.device("cuda")
# #Move `my_tensor` to device
# my_tensor = my_tensor.to(device)

# print("my_tensor device:", my_tensor.device)

Note that, we may not be able to see a performance boost with this tensor because it's already very small. However, switching devices will definitely speed up data preprocessing and models as we progress in later lessons.


**Tensor Slicing**

There are several ways to manipulate tensors. One important technique is slicing, where we use square brackets [] and indexing to select a subset of the values in a tensor.

In [12]:
# Slice my_tensor, assigning its top two rows to left_tensor and its bottom two rows to right_tensor
left_tensor = my_tensor[:2]
right_tensor = my_tensor[2:]

print("left_tensor class:", type(left_tensor))
print("left_tensor shape:", left_tensor.shape)
print("left_tensor data type:", left_tensor.dtype)
print("left_tensor device:", left_tensor.device)
print(left_tensor)
print() 
print("right_tensor class:", type(right_tensor))
print("right_tensor shape:", right_tensor.shape)
print("right_tensor data type:", right_tensor.dtype)
print("right_tensor device:", right_tensor.device)
print(right_tensor)

left_tensor class: <class 'torch.Tensor'>
left_tensor shape: torch.Size([2, 3])
left_tensor data type: torch.float32
left_tensor device: cpu
tensor([[1., 2., 3.],
        [4., 5., 6.]])

right_tensor class: <class 'torch.Tensor'>
right_tensor shape: torch.Size([2, 3])
right_tensor data type: torch.float32
right_tensor device: cpu
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


**Tensor Math**

Another way to manipulate tensors is to use mathematical operations. For example, we can perform addition using either the + operator or the `add()` method.

Note, these operations are useful when doing computer vision i.e deep learning.

In [13]:
summed_tensor_operator = left_tensor + right_tensor
summed_tensor_method = left_tensor.add(right_tensor)

print("summed_tensor_operator class:", type(summed_tensor_operator))
print("summed_tensor_operator shape:", summed_tensor_operator.shape)
print("summed_tensor_operator data type:", summed_tensor_operator.dtype)
print("summed_tensor_operator device:", summed_tensor_operator.device)
print(summed_tensor_operator)
print()
print("summed_tensor_method class:", type(summed_tensor_method))
print("summed_tensor_method shape:", summed_tensor_method.shape)
print("summed_tensor_method data type:", summed_tensor_method.dtype)
print("summed_tensor_method device:", summed_tensor_method.device)
print(summed_tensor_method)

summed_tensor_operator class: <class 'torch.Tensor'>
summed_tensor_operator shape: torch.Size([2, 3])
summed_tensor_operator data type: torch.float32
summed_tensor_operator device: cpu
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])

summed_tensor_method class: <class 'torch.Tensor'>
summed_tensor_method shape: torch.Size([2, 3])
summed_tensor_method data type: torch.float32
summed_tensor_method device: cpu
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])




One of the most important mathematical operations in deep learning is `multiplication`, so let's spend some time on it here.

Keep in mind that, when it comes to tensors, there's more than one type of multiplication. For starters, there's `element-wise multiplication`, where the corresponding values of two tensors are multiplied together. In PyTorch, we can do this using the * operator or the `.mul()` method.

In [14]:
ew_tensor_operator = left_tensor * right_tensor
ew_tensor_method = left_tensor.mul(right_tensor)

print("ew_tensor_operator class:", type(ew_tensor_operator))
print("ew_tensor_operator shape:", ew_tensor_operator.shape)
print("ew_tensor_operator data type:", ew_tensor_operator.dtype)
print("ew_tensor_operator device:", ew_tensor_operator.device)
print(ew_tensor_operator)
print()
print("ew_tensor_method class:", type(ew_tensor_method))
print("ew_tensor_method shape:", ew_tensor_method.shape)
print("ew_tensor_method data type:", ew_tensor_method.dtype)
print("ew_tensor_method device:", ew_tensor_method.device)
print(ew_tensor_method)

ew_tensor_operator class: <class 'torch.Tensor'>
ew_tensor_operator shape: torch.Size([2, 3])
ew_tensor_operator data type: torch.float32
ew_tensor_operator device: cpu
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])

ew_tensor_method class: <class 'torch.Tensor'>
ew_tensor_method shape: torch.Size([2, 3])
ew_tensor_method data type: torch.float32
ew_tensor_method device: cpu
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])


Note that element-wise multiplication is `commutative`. It doesn't matter in what order we multiply the two tensors. The product of left_tensor * right_tensor is the same as the product of right_tensor * left_tensor.

In [15]:
left_tensor * right_tensor == right_tensor * left_tensor

tensor([[True, True, True],
        [True, True, True]])

Next is the `Matrix multiplication`, which combines the rows and columns of two tensors to generate a new one. We can use the @ operator or the `.matmul()` method.

To see how this works, let's create two new tensors with different shapes.

In [16]:
new_left_tensor = torch.Tensor([[2, 5], [7, 3]])
new_right_tensor = torch.Tensor([[8], [9]])

print("new_left_tensor class:", type(new_left_tensor))
print("new_left_tensor shape:", new_left_tensor.shape)
print("new_left_tensor data type:", new_left_tensor.dtype)
print("new_left_tensor device:", new_left_tensor.device)
print(new_left_tensor)
print()
print("new_right_tensor class:", type(new_right_tensor))
print("new_right_tensor shape:", new_right_tensor.shape)
print("new_right_tensor data type:", new_right_tensor.dtype)
print("new_right_tensor device:", new_right_tensor.device)
print(new_right_tensor)

new_left_tensor class: <class 'torch.Tensor'>
new_left_tensor shape: torch.Size([2, 2])
new_left_tensor data type: torch.float32
new_left_tensor device: cpu
tensor([[2., 5.],
        [7., 3.]])

new_right_tensor class: <class 'torch.Tensor'>
new_right_tensor shape: torch.Size([2, 1])
new_right_tensor data type: torch.float32
new_right_tensor device: cpu
tensor([[8.],
        [9.]])


In [17]:
mm_tensor_operator = new_left_tensor @ new_right_tensor
mm_tensor_method = new_left_tensor.matmul(new_right_tensor)

print("mm_tensor_operator class:", type(mm_tensor_operator))
print("mm_tensor_operator shape:", mm_tensor_operator.shape)
print("mm_tensor_operator data type:", mm_tensor_operator.dtype)
print("mm_tensor_operator device:", mm_tensor_operator.device)
print(mm_tensor_operator)
print()
print("mm_tensor_method class:", type(mm_tensor_method))
print("mm_tensor_method shape:", mm_tensor_method.shape)
print("mm_tensor_method data type:", mm_tensor_method.dtype)
print("mm_tensor_method device:", mm_tensor_method.device)
print(mm_tensor_method)

mm_tensor_operator class: <class 'torch.Tensor'>
mm_tensor_operator shape: torch.Size([2, 1])
mm_tensor_operator data type: torch.float32
mm_tensor_operator device: cpu
tensor([[61.],
        [83.]])

mm_tensor_method class: <class 'torch.Tensor'>
mm_tensor_method shape: torch.Size([2, 1])
mm_tensor_method data type: torch.float32
mm_tensor_method device: cpu
tensor([[61.],
        [83.]])


One very important thing to remember: `matrix multiplication` is not `commutative`. The number of columns in the tensor on the left must equal the number of rows in the tensor on the right. If these two dimensions don't match, your code will throw a `RunTimeError`.

In [ ]:
# mm_tensor_operator = new_right_tensor @ new_left_tensor

*Matrix multiplication is the way your models will train and make predictions, and dimension mismatches will be a common source of bugs when you start building models. For that reason, it's always important to check the shape of your tensors. 🤓*

Lastly, tensors come with methods for `aggregation calculations`. For instance, if we wanted to know the mean of all the elements in my_tensor, we'd use the `.mean()` method.

In [18]:
print(my_tensor)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [19]:
my_tensor_mean = my_tensor.mean()

print("my_tensor_mean class:", type(my_tensor_mean))
print("my_tensor_mean shape:", my_tensor_mean.shape)
print("my_tensor_mean data type:", my_tensor_mean.dtype)
print("my_tensor_mean device:", my_tensor_mean.device)
print("my_tensor mean:", my_tensor_mean)

my_tensor_mean class: <class 'torch.Tensor'>
my_tensor_mean shape: torch.Size([])
my_tensor_mean data type: torch.float32
my_tensor_mean device: cpu
my_tensor mean: tensor(6.5000)


Using `.mean()` by itself is helpful if we want to aggregate all the elements in a tensor, but more often we want to aggregate along one of the tensor's axes.

For example, what's the mean of each column in my_tensor? Remember that the dimensions of this tensor: [4, 3]. The first number in this list refers to the `4 rows`, and the second to `3 columns`. If we want the mean of each column, we need to reduce across the rows or first dimension. To do this, we use the `dim=` argument. And since Python uses 0-based indexing, we specify the first dimension with a 0.

In [20]:
my_tensor

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [21]:
my_tensor_column_means = my_tensor.mean(dim=[0])

print("my_tensor_column_means class:", type(my_tensor_column_means))
print("my_tensor_column_means shape:", my_tensor_column_means.shape)
print("my_tensor_column_means data type:", my_tensor_column_means.dtype)
print("my_tensor_column_means device:", my_tensor_column_means.device)
print("my_tensor column means:", my_tensor_column_means)

my_tensor_column_means class: <class 'torch.Tensor'>
my_tensor_column_means shape: torch.Size([3])
my_tensor_column_means data type: torch.float32
my_tensor_column_means device: cpu
my_tensor column means: tensor([5.5000, 6.5000, 7.5000])


`.mean(dim=[0])` is computing **column-wise means** of a tensor.

Let’s break it down precisely:

### The operation

```python
my_tensor_column_means = my_tensor.mean(dim=[0])
```

### What it does

* `mean()` computes the arithmetic average.
* `dim=[0]` tells PyTorch to **reduce (collapse) dimension 0**.

### Interpretation

If `my_tensor` is a 2D tensor shaped like:

```
(rows, columns)
```

then:

* `dim=0` → operate **down the rows**
* result → one value per column

So you're averaging **each column across all rows**.

### Concrete example

```python
import torch

my_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
```

Applying:

```python
my_tensor.mean(dim=0)
```

Result:

```
tensor([4., 5., 6.])
```

Why?

* Column 1 → (1 + 4 + 7) / 3 = 4
* Column 2 → (2 + 5 + 8) / 3 = 5
* Column 3 → (3 + 6 + 9) / 3 = 6

### General intuition

* `dim=0` → collapse rows → get **column statistics**
* `dim=1` → collapse columns → get **row statistics**

We now have some `helpful tools for working with PyTorch tensors`.
- We can check a tensor's shape, data type and device.
- We can manipulate a tensor by slicing it. We can perform mathematical operations on tensors, including matrix multiplication and aggregation calculations.

Up next, let's apply our new skills by exploring the dataset for this project.

**NOTE**: There are many tensors functions which we've not yet discussed about, head over to the **pytorch** (https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html) library for more information.